

# UI App properties

env.URL = https://www.saucedemo.com/

env.loginUser1 = standard_user
env.loginUser1_password = secret_sauce
#env.loginUser2=
#env.loginUser2_password=

env.reqresapi.uri = https://reqres.in/api/users