webdriver.browser=chrome
webdriver.video=false
#webdriver.gridurl=

#Edge default location
edge.location = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"

#Browserstack Properties
browserstack.test=Y
browserstack.user=meganathanramasa_kVh4fi
browserstack.accesskey=3uKcq66msjjy7ELxvqHa
browserstack.url=https://%s:%s@hub.browserstack.com/wd/hub

browserstack.accept.ssl.certs=true
browserstack.os=windows
browserstack.os_version=10
browserstack.browser=chrome
browserstack.browser_version=108

browserstack.local=false
browserstackLocal.useproxy=false
browserstackLocal.proxy.host=
browserstackLocal.proxy.port=