# bdd.times.out     = max timeout for each story
# bdd.thread        = parallel execution threads
# Project.Name      = project name
# test.environment  = testing environment
# bdd.metaFilter    = meta filter for execution
# bdd.seqMetaFilter = meta filter for pre-execution
#
bdd.times.out=2000
bdd.thread=1
Project.Name=TestProject
test.environment=env
bdd.metaFilter=
bdd.seqMetaFilter=